### ISSUE TITLE
TW and Media Sources

### ISSUE THREAD

**Issue by BobRay** [donShakespeare/tinymce_wrapper#4]
I may have things configured wrong, but elFinder seems to have trouble when an image TV has a media source for the context the resource is in.

MODX prepends the Media Source's baseUrl when producing the image tag.  It also does so when producing the thumbnail for the TV value's preview in the Manager.

In the front end, the site_url is prepended to all of that by the base href tag. 

So, if the Media Source baseURL is assets/images/ and the file is picture.jpg, the correct content of the TV's input on the Create/Edit Resource page would be picture.jpg.  elFinder is putting this there for me: /addons/assets/images/compass-vector.jpg, so the image tag is invalid and there is no preview in the Manager.

**Comment by donShakespeare** [comment]
You need to edit the elFinder browser callback to further refine returned URL according to the resource's media source demands. I'll whip something up.

**Comment by BobRay** [comment]
I figured out how to do that, but since the code is JavaScript, visible in the browser, can't miscreants edit it and browse anywhere?

BTW, here's some code that might be useful:

$ctx = '';
// $ctx = $resource->get('contextKey');
$ctx = empty($ctx) ? 'web' : $ctx;

$tv = $modx->getObject('modTemplateVar', array('name' => 'ImageTV'));
$source = $tv->getSource($ctx, false);
$properties = $source->getProperties();
// var_dump($properties);

echo "\n<br /> baseURL: " . $properties['baseUrl']['value'];
echo "\n<br /> basePath: " . $properties['basePath']['value'];

exit;

**Comment by donShakespeare** [comment]
Where are you echoing this stuff to? to be annexed to the image filename?

No, elFinder gets its volume basepath, conclusively, server-side; no worry about them miscreant knaves.

**Comment by JoeBlow** [comment]
Good to know. Thanks :)
